version: '3.8'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    container_name: foodgram-db
    env_file: ../.env.example
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    container_name: foodgram-backend
    build: ../backend/
    env_file: ../.env.example
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/app/media

  frontend:
    env_file: ../.env.example
    container_name: foodgram-frontend
    build: ../frontend/
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static

  nginx:
    image: nginx:1.25.4-alpine
    container_name: foodgram-proxy
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static:/staticfiles/
      - media:/media/


